/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projectepyc.view.gui.InfoClub;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import com.mycompany.projectepyc.model.Participant;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class InfoClubJTable extends javax.swing.JDialog {

    private GestorAEPDA gestor;
    private String nombreClub;
    private ArrayList<Participant> copiaParticipants;
    /**
     * Creates new form InfoClubJTablee
     */
    public InfoClubJTable(java.awt.Frame parent, boolean modal, GestorAEPDA gestor, String nombreClub) throws SQLException{
        super(parent,modal);
        this.gestor = gestor;
        this.nombreClub = nombreClub;
        cargarParticipants();
        initComponents();
        this.setLocationRelativeTo(null);
        
        jLabel1.setText("Participants del club: " + nombreClub);
        
        cargarTabla();
    }
    
    public InfoClubJTable(java.awt.Frame parent, boolean modal, GestorAEPDA gestor, String nombreClub, ArrayList<Participant> participants) throws SQLException {
        super(parent,modal);
        this.gestor = gestor;
        this.nombreClub = nombreClub;
        this.copiaParticipants = participants;
        initComponents();
        this.setLocationRelativeTo(null);
        
        jLabel1.setText("Participants del club: " + nombreClub);
        
        cargarTabla();
    }
    
    private void cargarParticipants() throws SQLException {
        try {
            copiaParticipants = gestor.getCopiaParticipants(nombreClub);
        } catch(AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error obtenint participants: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);            
        }
    }
    
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) TaulaParticipants.getModel();
        modeloTabla.setRowCount(0);
        if(copiaParticipants != null) {
            int numeroColumnasTabla = TaulaParticipants.getColumnCount();
            
            for(Participant p : copiaParticipants) {
                Object[] objetoParaFilaDeTaba = new Object[numeroColumnasTabla];
                objetoParaFilaDeTaba[0] = p.getID();
                objetoParaFilaDeTaba[1] = p.getNickname();
                
                modeloTabla.addRow(objetoParaFilaDeTaba);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaulaParticipants = new javax.swing.JTable();
        Enrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nom del club");

        TaulaParticipants.setBackground(new java.awt.Color(255, 255, 255));
        TaulaParticipants.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TaulaParticipants.setForeground(new java.awt.Color(0, 0, 0));
        TaulaParticipants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nickname"
            }
        ));
        jScrollPane1.setViewportView(TaulaParticipants);

        Enrere.setBackground(new java.awt.Color(22, 20, 20));
        Enrere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Enrere.setForeground(new java.awt.Color(255, 255, 255));
        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Enrere)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enrere)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EnrereActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrere;
    private javax.swing.JTable TaulaParticipants;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
