/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectepyc.view.gui.InfoClub;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import com.mycompany.projectepyc.model.Participant;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author Mario
 */
public class InfoClubSelector extends javax.swing.JFrame {
    
    
    private GestorAEPDA gestor;
    private ArrayList<Participant> listaParticipantesClubActual;
    /**
     * Creates new form IngoClubSelector
     */
    public InfoClubSelector(GestorAEPDA gestor) {
        this.gestor = gestor;
        initComponents();
        this.setLocationRelativeTo(null);
        
        cargarClubesComboBox();
    }
    
    private void cargarClubesComboBox() throws SQLException{
        jComB_ClubesDisponibles.removeAllItems();
        
        ArrayList<String> copiaClubes = gestor.getCopiaNombresClubs();
        if(copiaClubes.isEmpty()) {
            jComB_ClubesDisponibles.addItem("No hi ha clubs");
            jComB_ClubesDisponibles.setEnabled(false);
            veureInfo.setEnabled(false);
        } else {
            for(String n : copiaClubes) {
                jComB_ClubesDisponibles.addItem(n);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComB_ClubesDisponibles = new javax.swing.JComboBox<>();
        Enrere = new javax.swing.JButton();
        veureInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecciona club:");

        jComB_ClubesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComB_ClubesDisponiblesActionPerformed(evt);
            }
        });

        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        veureInfo.setText("Ver Info");
        veureInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veureInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComB_ClubesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Enrere, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(veureInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jComB_ClubesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enrere)
                    .addComponent(veureInfo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComB_ClubesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComB_ClubesDisponiblesActionPerformed
        // Afafo el nom de la nau del ComboBox.
        String nombreClubSeleccionado = (String) jComB_ClubesDisponibles.getSelectedItem();

        if (nombreClubSeleccionada == null || nombreClubSeleccionada.equals("No hi ha naus")) {
            return;
        }

        listaAstronautasNaveActual = getListaAstronautaYGestionBoton(nombreNaveSeleccionada);
    }//GEN-LAST:event_jComB_ClubesDisponiblesActionPerformed

    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EnrereActionPerformed

    private void veureInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veureInfoActionPerformed
        String nombreClubSeleccionado = (String) jComB_ClubesDisponibles.getSelectedItem();

        try {
            if (listaParticipantesClubActual == null) {
                throw new AEPDAException("Error, selecciona un club");
            }

            if (listaParticipantesClubActual.isEmpty()) {
                throw new AEPDAException("El club " + nombreClubSeleccionado + " no tiene particpantes apuntados ahora mismo.");
            }

            // Aquí hi ha nau i no està buida! Perfecte, ara sí hem de obrir el nou dialeg.
            // Recupero el JFrame pare
            JFrame mainJFramePare = (JFrame) this.getParent();

            // ja no necessito dades del dialeg.
            this.dispose();

            InfoNaveJTable infoNaveJTable = new InfoNaveJTable(mainJFramePare, true, gestor, nombreNaveSeleccionada, listaAstronautasNaveActual);
            infoNaveJTable.setVisible(true);
        } catch (GalaxiaException ex) {
            JOptionPane.showMessageDialog(this, "Error seleccionando nave: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_veureInfoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrere;
    private javax.swing.JComboBox<String> jComB_ClubesDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton veureInfo;
    // End of variables declaration//GEN-END:variables
}
