/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectepyc.view.gui.InfoClub;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import com.mycompany.projectepyc.model.Participant;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class InfoClubSelector extends javax.swing.JDialog {
    
    
    private GestorAEPDA gestor;
    private ArrayList<Participant> listaParticipantesClubActual;
    private JFrame ventanaPare;
    /**
     * Creates new form IngoClubSelector
     */
    public InfoClubSelector(java.awt.Frame parent, boolean modal,GestorAEPDA gestor) throws SQLException {
        super(parent,modal);
        this.ventanaPare = (JFrame) parent;
        this.gestor = gestor;
        initComponents();
        this.setLocationRelativeTo(null);
        
        cargarClubesComboBox();
    }
    
    private void cargarClubesComboBox() throws SQLException{
        jComB_ClubesDisponibles.removeAllItems();
        
        ArrayList<String> copiaClubes = gestor.getCopiaNombresClubs();
        if(copiaClubes.isEmpty()) {
            jComB_ClubesDisponibles.addItem("No hi ha clubs");
            jComB_ClubesDisponibles.setEnabled(false);
            veureInfo.setEnabled(false);
        } else {
            for(String n : copiaClubes) {
                jComB_ClubesDisponibles.addItem(n);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComB_ClubesDisponibles = new javax.swing.JComboBox<>();
        Enrere = new javax.swing.JButton();
        veureInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecciona club:");

        jComB_ClubesDisponibles.setBackground(new java.awt.Color(22, 20, 20));
        jComB_ClubesDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComB_ClubesDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        jComB_ClubesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComB_ClubesDisponiblesActionPerformed(evt);
            }
        });

        Enrere.setBackground(new java.awt.Color(22, 20, 20));
        Enrere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Enrere.setForeground(new java.awt.Color(255, 255, 255));
        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        veureInfo.setBackground(new java.awt.Color(22, 20, 20));
        veureInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        veureInfo.setForeground(new java.awt.Color(255, 255, 255));
        veureInfo.setText("Ver Info");
        veureInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veureInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Enrere, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(veureInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComB_ClubesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jComB_ClubesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enrere)
                    .addComponent(veureInfo))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComB_ClubesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComB_ClubesDisponiblesActionPerformed
        // Afafo el nom de la nau del ComboBox.
        String nombreClubSeleccionado = (String) jComB_ClubesDisponibles.getSelectedItem();

        if (nombreClubSeleccionado == null || nombreClubSeleccionado.equals("No hi ha naus")) {
            return;
        }

        try {
            listaParticipantesClubActual = getListaParticipantSinGestionBoton(nombreClubSeleccionado);
        } catch (SQLException ex) {
            Logger.getLogger(InfoClubSelector.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComB_ClubesDisponiblesActionPerformed

    private ArrayList<Participant> getListaParticipantSinGestionBoton(String nombreClub) throws SQLException {
        ArrayList<Participant> listaParticipants = new ArrayList<>();
        try{
            listaParticipants = gestor.getCopiaParticipants(nombreClub);
        } catch (AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error seleccionant club: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return listaParticipants;
    }
    
    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EnrereActionPerformed

    private void veureInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veureInfoActionPerformed
        String nombreClubSeleccionado = (String) jComB_ClubesDisponibles.getSelectedItem();

        try {
            if (listaParticipantesClubActual == null) {
                throw new AEPDAException("Error, selecciona un club");
            }

            if (listaParticipantesClubActual.isEmpty()) {
                throw new AEPDAException("El club " + nombreClubSeleccionado + " no tiene particpantes apuntados ahora mismo.");
            }

            JFrame mainJFramePare = (JFrame) this.ventanaPare;

            this.dispose();

            InfoClubJTable infoClubJTable = new InfoClubJTable(mainJFramePare, true, gestor, nombreClubSeleccionado, listaParticipantesClubActual);
            infoClubJTable.setVisible(true);
        } catch (AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error seleccionant club: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error seleccionant club: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_veureInfoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrere;
    private javax.swing.JComboBox<String> jComB_ClubesDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton veureInfo;
    // End of variables declaration//GEN-END:variables
}
