/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectepyc.view.gui;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import com.mycompany.projectepyc.view.gui.InfoClub.InfoClubSelector;
import com.mycompany.projectepyc.view.gui.sorteig.SeleccioJocSorteigJDialog;
import com.mycompany.projectepyc.view.gui.taules.SeleccionarJocLlistatJDialog;
import com.mycompany.projectepyc.view.gui.taules.SeleccionarJocTaulaJDialog;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class MainJFrame extends javax.swing.JFrame {

    private GestorAEPDA gestor;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() throws IOException, AEPDAException {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            gestor = new GestorAEPDA();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos IO: \n" + ex.getMessage(), "Error.", JOptionPane.ERROR_MESSAGE);
        } catch (AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error en la aplicacion AEPDA: \n" + ex.getMessage(), "Error.", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Sortir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegistrarClub = new javax.swing.JMenuItem();
        RegistrarParticipant = new javax.swing.JMenuItem();
        ModificarParticipant = new javax.swing.JMenuItem();
        EsborrarParticipant = new javax.swing.JMenuItem();
        LlistatClubs = new javax.swing.JMenuItem();
        MembresClub = new javax.swing.JMenuItem();
        RegistrarTaula = new javax.swing.JMenuItem();
        LlistatTaules = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AEPDA");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Aquesta aplicació permet registrar clubs,");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("participants i taules per als jocs KillTeam i MESBG");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("També mostra tota la informació necesaria per als tornejos");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("I porta incorporat un generador de sortejos automàtic");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("per poder iniciar amb la primera ronda !");

        Sortir.setBackground(new java.awt.Color(22, 20, 20));
        Sortir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sortir.setForeground(new java.awt.Color(255, 255, 255));
        Sortir.setText("Sortir");
        Sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sortir)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(Sortir)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Opcions");

        RegistrarClub.setBackground(new java.awt.Color(0, 153, 255));
        RegistrarClub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistrarClub.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarClub.setText("Registrar Club");
        RegistrarClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClubActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarClub);

        RegistrarParticipant.setBackground(new java.awt.Color(0, 153, 255));
        RegistrarParticipant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistrarParticipant.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarParticipant.setText("Registrar Participant");
        RegistrarParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarParticipantActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarParticipant);

        ModificarParticipant.setBackground(new java.awt.Color(0, 153, 255));
        ModificarParticipant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModificarParticipant.setForeground(new java.awt.Color(0, 0, 0));
        ModificarParticipant.setText("Modificar Participant");
        ModificarParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarParticipantActionPerformed(evt);
            }
        });
        jMenu1.add(ModificarParticipant);

        EsborrarParticipant.setBackground(new java.awt.Color(0, 153, 255));
        EsborrarParticipant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EsborrarParticipant.setForeground(new java.awt.Color(0, 0, 0));
        EsborrarParticipant.setText("Esborrar Participant");
        EsborrarParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsborrarParticipantActionPerformed(evt);
            }
        });
        jMenu1.add(EsborrarParticipant);

        LlistatClubs.setBackground(new java.awt.Color(0, 153, 255));
        LlistatClubs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LlistatClubs.setForeground(new java.awt.Color(0, 0, 0));
        LlistatClubs.setText("Llistat Clubs");
        LlistatClubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlistatClubsActionPerformed(evt);
            }
        });
        jMenu1.add(LlistatClubs);

        MembresClub.setBackground(new java.awt.Color(0, 153, 255));
        MembresClub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MembresClub.setForeground(new java.awt.Color(0, 0, 0));
        MembresClub.setText("Mostrar Membres d'un Club");
        MembresClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MembresClubActionPerformed(evt);
            }
        });
        jMenu1.add(MembresClub);

        RegistrarTaula.setBackground(new java.awt.Color(0, 153, 255));
        RegistrarTaula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistrarTaula.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarTaula.setText("Registrar Taula");
        RegistrarTaula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarTaulaActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarTaula);

        LlistatTaules.setBackground(new java.awt.Color(0, 153, 255));
        LlistatTaules.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LlistatTaules.setForeground(new java.awt.Color(0, 0, 0));
        LlistatTaules.setText("Llistat Taules");
        LlistatTaules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlistatTaulesActionPerformed(evt);
            }
        });
        jMenu1.add(LlistatTaules);

        jMenuItem5.setBackground(new java.awt.Color(0, 153, 255));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem5.setText("Generar Sorteig 1a Ronda");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClubActionPerformed
        // TODO add your handling code here:
        AltaClubJDialog altaDialogC = new AltaClubJDialog(this,true,gestor);
        altaDialogC.setVisible(true);
    }//GEN-LAST:event_RegistrarClubActionPerformed

    private void RegistrarParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarParticipantActionPerformed
        // TODO add your handling code here:
        AltaParticipantJDialog altaDialogP = new AltaParticipantJDialog(this,true,gestor);
        altaDialogP.setVisible(true);
    }//GEN-LAST:event_RegistrarParticipantActionPerformed

    private void ModificarParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarParticipantActionPerformed
        // TODO add your handling code here:
        ModificarParticipantJDialog modificarPDialog = new ModificarParticipantJDialog(this,true,gestor);
        modificarPDialog.setVisible(true);
    }//GEN-LAST:event_ModificarParticipantActionPerformed

    private void EsborrarParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsborrarParticipantActionPerformed
        // TODO add your handling code here:
        BorrarParticipantJDialog borrarJDialog = new BorrarParticipantJDialog(this,true,gestor);
        borrarJDialog.setVisible(true);
    }//GEN-LAST:event_EsborrarParticipantActionPerformed

    private void MembresClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MembresClubActionPerformed
        // TODO add your handling code here:
        InfoClubSelector infoClubSelector;
        try {
            infoClubSelector = new InfoClubSelector(this,true,gestor);
            infoClubSelector.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MembresClubActionPerformed

    private void RegistrarTaulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarTaulaActionPerformed
        // TODO add your handling code here:
        SeleccionarJocTaulaJDialog SeleccionarJocJDialog = new SeleccionarJocTaulaJDialog(this, true, gestor);
        SeleccionarJocJDialog.setVisible(true);
    }//GEN-LAST:event_RegistrarTaulaActionPerformed

    private void LlistatTaulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlistatTaulesActionPerformed
        // TODO add your handling code here:
        SeleccionarJocLlistatJDialog SeleccionarJocJDialog = new SeleccionarJocLlistatJDialog(this, true, gestor);
        SeleccionarJocJDialog.setVisible(true);
    }//GEN-LAST:event_LlistatTaulesActionPerformed

    private void SortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SortirActionPerformed

    private void LlistatClubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlistatClubsActionPerformed
        // TODO add your handling code here:
        LlistatClubsJDialog clubsJDialog;
        try {
            clubsJDialog = new LlistatClubsJDialog(this, true, gestor);
            clubsJDialog.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LlistatClubsActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        SeleccioJocSorteigJDialog SorteigJDialog = new SeleccioJocSorteigJDialog(this, true, gestor);
        SorteigJDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EsborrarParticipant;
    private javax.swing.JMenuItem LlistatClubs;
    private javax.swing.JMenuItem LlistatTaules;
    private javax.swing.JMenuItem MembresClub;
    private javax.swing.JMenuItem ModificarParticipant;
    private javax.swing.JMenuItem RegistrarClub;
    private javax.swing.JMenuItem RegistrarParticipant;
    private javax.swing.JMenuItem RegistrarTaula;
    private javax.swing.JButton Sortir;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
