/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectepyc.view.gui;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class ModificarParticipantJDialog extends javax.swing.JDialog {

    
    private GestorAEPDA gestor;
    /**
     * Creates new form ModificarParticipant
     */
    public ModificarParticipantJDialog(java.awt.Frame parent, boolean modal, GestorAEPDA gestor) {
        super(parent, modal);
        this.gestor = gestor;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtF_ID = new javax.swing.JTextField();
        jTxtF_NouNickname = new javax.swing.JTextField();
        jBut_ModificarParticipant = new javax.swing.JButton();
        jBut_Enrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Modificar Participant");

        jLabel2.setText("ID");

        jLabel3.setText("Nou Nickname");

        jTxtF_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtF_IDActionPerformed(evt);
            }
        });

        jTxtF_NouNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtF_NouNicknameActionPerformed(evt);
            }
        });

        jBut_ModificarParticipant.setText("Modificar");
        jBut_ModificarParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ModificarParticipantActionPerformed(evt);
            }
        });

        jBut_Enrere.setText("Enrere");
        jBut_Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_EnrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(98, 98, 98)
                                .addComponent(jTxtF_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut_Enrere)
                                .addGap(38, 38, 38)
                                .addComponent(jBut_ModificarParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(jTxtF_NouNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtF_NouNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut_ModificarParticipant)
                    .addComponent(jBut_Enrere))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtF_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtF_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtF_IDActionPerformed

    private void jTxtF_NouNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtF_NouNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtF_NouNicknameActionPerformed

    private void jBut_ModificarParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ModificarParticipantActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTxtF_ID.getText());
        String nouNickname = jTxtF_NouNickname.getText();
        
        try {
            gestor.modificarParticipant(id, nouNickname);

            JOptionPane.showMessageDialog(this, "Nickname del participant modificat correctament", "Ok", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error de la app modificant el nickname del participant: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(AltaClubJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBut_ModificarParticipantActionPerformed

    private void jBut_EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBut_EnrereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Enrere;
    private javax.swing.JButton jBut_ModificarParticipant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTxtF_ID;
    private javax.swing.JTextField jTxtF_NouNickname;
    // End of variables declaration//GEN-END:variables
}
