/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projectepyc.view.gui.taules;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import com.mycompany.projectepyc.view.gui.AltaClubJDialog;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class AltaTaulaMESBGJDialog extends javax.swing.JDialog {

    private GestorAEPDA gestor;
    /**
     * Creates new form AltaTaulaMESBG
     */
    public AltaTaulaMESBGJDialog(java.awt.Frame parent, boolean modal, GestorAEPDA gestor) {
        super(parent, modal);
        this.gestor = gestor;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Escenari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Enrere = new javax.swing.JButton();
        jBut_GuardarTaulaMESBG = new javax.swing.JButton();
        SeleccionarID = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ALTA TAULA MESBG");

        jLabel2.setText("Número de la Taula:");

        Escenari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscenariActionPerformed(evt);
            }
        });

        jLabel3.setText("Escenari:");

        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        jBut_GuardarTaulaMESBG.setText("Guardar");
        jBut_GuardarTaulaMESBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_GuardarTaulaMESBGActionPerformed(evt);
            }
        });

        SeleccionarID.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(Enrere))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Escenari, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jBut_GuardarTaulaMESBG, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(SeleccionarID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SeleccionarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Escenari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enrere)
                    .addComponent(jBut_GuardarTaulaMESBG))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EnrereActionPerformed

    private void jBut_GuardarTaulaMESBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_GuardarTaulaMESBGActionPerformed
        int numeroTaula = (Integer) SeleccionarID.getValue();
        String escenari = Escenari.getText();

        try {
            gestor.addMesaMESBG(numeroTaula, escenari);
            JOptionPane.showMessageDialog(this, "Taula per a KillTeam registrada correctament", "Ok", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error de sistema registrant la taula per a MESBG: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error de la app registrant la taula per a MESBG: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de la app registrant la taula per a MESBG: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBut_GuardarTaulaMESBGActionPerformed

    private void EscenariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscenariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscenariActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrere;
    private javax.swing.JTextField Escenari;
    private javax.swing.JSpinner SeleccionarID;
    private javax.swing.JButton jBut_GuardarTaulaMESBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
