/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projectepyc.view.gui.taules;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import com.mycompany.projectepyc.model.TaulaKillTeam;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class LlistatTaulesKillTeamJDialog extends javax.swing.JDialog {

    private GestorAEPDA gestor;
    private ArrayList<TaulaKillTeam> copiaTaulesKillTeam;

    /**
     * Creates new form LlistatTaulesKillTeamJDialog
     */
    public LlistatTaulesKillTeamJDialog(java.awt.Frame parent, boolean modal, GestorAEPDA gestor) throws SQLException {
        super(parent, modal);
        this.gestor = gestor;
        cargarTaulesKillTeam();
        initComponents();
        this.setLocationRelativeTo(null);

        cargarTabla();
    }

    public LlistatTaulesKillTeamJDialog(java.awt.Frame parent, boolean modal, GestorAEPDA gestor, ArrayList<TaulaKillTeam> taulesKillTeam) throws SQLException {
        super(parent, modal);
        this.gestor = gestor;
        this.copiaTaulesKillTeam = taulesKillTeam;
        initComponents();
        this.setLocationRelativeTo(null);

        cargarTabla();
    }

    public void cargarTaulesKillTeam() throws SQLException {
        try {
            copiaTaulesKillTeam = gestor.getCopiaTaulesKillTeam();
        } catch (AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error obtenint les taules de KillTeam: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) TaulaTaulesKillTeam.getModel();
        modeloTabla.setRowCount(0);
        if(copiaTaulesKillTeam != null) {
            int numeroColumnasTabla = TaulaTaulesKillTeam.getColumnCount();
            
            for(TaulaKillTeam t : copiaTaulesKillTeam) {
                Object[] objetoParaFilaDeTaba = new Object[numeroColumnasTabla];
                objetoParaFilaDeTaba[0] = t.getNumero();
                objetoParaFilaDeTaba[1] = t.getAmbient();
                
                modeloTabla.addRow(objetoParaFilaDeTaba);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaulaTaulesKillTeam = new javax.swing.JTable();
        Enrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LLISTAT DE TAULES DE KILLTEAM");

        TaulaTaulesKillTeam.setBackground(new java.awt.Color(255, 255, 255));
        TaulaTaulesKillTeam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TaulaTaulesKillTeam.setForeground(new java.awt.Color(0, 0, 0));
        TaulaTaulesKillTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero Taula", "Ambient"
            }
        ));
        jScrollPane1.setViewportView(TaulaTaulesKillTeam);

        Enrere.setBackground(new java.awt.Color(0, 0, 0));
        Enrere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Enrere.setForeground(new java.awt.Color(255, 255, 255));
        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Enrere)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Enrere)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EnrereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrere;
    private javax.swing.JTable TaulaTaulesKillTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
