/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projectepyc.view.gui.taules;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import com.mycompany.projectepyc.exception.AEPDAException;
import com.mycompany.projectepyc.model.TaulaMESBG;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class LlistatTaulesMESBGJDialog extends javax.swing.JDialog {

    private GestorAEPDA gestor;
    private ArrayList<TaulaMESBG> copiaTaulesMESBG;
    /**
     * Creates new form LlistatTaulesKillTeamJDialog
     */
    public LlistatTaulesMESBGJDialog(java.awt.Frame parent, boolean modal, GestorAEPDA gestor) throws SQLException {
        super(parent, modal);
        this.gestor = gestor;
        cargarTaulesMESBG();
        initComponents();
        this.setLocationRelativeTo(null);

        cargarTabla();
    }

    public LlistatTaulesMESBGJDialog(java.awt.Frame parent, boolean modal, GestorAEPDA gestor, ArrayList<TaulaMESBG> taulesMESBG) throws SQLException {
        super(parent, modal);
        this.gestor = gestor;
        this.copiaTaulesMESBG = taulesMESBG;
        initComponents();
        this.setLocationRelativeTo(null);

        cargarTabla();
    }
    
    public void cargarTaulesMESBG() throws SQLException {
        try {
            copiaTaulesMESBG = gestor.getCopiaTaulesMESBG();
        } catch (AEPDAException ex) {
            JOptionPane.showMessageDialog(this, "Error obtenint les taules de KillTeam: \n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) TaulaTaulesMESBG.getModel();
        modeloTabla.setRowCount(0);
        if(copiaTaulesMESBG != null) {
            int numeroColumnasTabla = TaulaTaulesMESBG.getColumnCount();
            
            for(TaulaMESBG t : copiaTaulesMESBG) {
                Object[] objetoParaFilaDeTaba = new Object[numeroColumnasTabla];
                objetoParaFilaDeTaba[0] = t.getNumero();
                objetoParaFilaDeTaba[1] = t.getEscenari();
                
                modeloTabla.addRow(objetoParaFilaDeTaba);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaulaTaulesMESBG = new javax.swing.JTable();
        Enrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("LLISTAT DE TAULES DE MESBG");

        TaulaTaulesMESBG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero Taula", "Escenari"
            }
        ));
        jScrollPane1.setViewportView(TaulaTaulesMESBG);

        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Enrere)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enrere)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EnrereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrere;
    private javax.swing.JTable TaulaTaulesMESBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
