/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projectepyc.view.gui.taules;

import com.mycompany.projectepyc.controller.GestorAEPDA;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class SeleccionarJocTaulaJDialog extends javax.swing.JDialog {

    private GestorAEPDA gestor;
    private JFrame ventanaPare;
    /**
     * Creates new form AltaTaula
     */
    public SeleccionarJocTaulaJDialog(java.awt.Frame parent, boolean modal, GestorAEPDA gestor) {
        super(parent, modal);
        this.ventanaPare = (JFrame) parent;
        this.gestor = gestor;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jBut_GuardarParticipant = new javax.swing.JButton();
        Enrere = new javax.swing.JButton();
        seleccionador = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jBut_GuardarParticipant.setBackground(new java.awt.Color(0, 0, 0));
        jBut_GuardarParticipant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBut_GuardarParticipant.setForeground(new java.awt.Color(255, 255, 255));
        jBut_GuardarParticipant.setText("Seleccionar");
        jBut_GuardarParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_GuardarParticipantActionPerformed(evt);
            }
        });

        Enrere.setBackground(new java.awt.Color(0, 0, 0));
        Enrere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Enrere.setForeground(new java.awt.Color(255, 255, 255));
        Enrere.setText("Enrere");
        Enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereActionPerformed(evt);
            }
        });

        seleccionador.setBackground(new java.awt.Color(0, 0, 0));
        seleccionador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seleccionador.setForeground(new java.awt.Color(255, 255, 255));
        seleccionador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KillTeam", "MESBG" }));
        seleccionador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionadorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Selecciona joc:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRAR TAULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(seleccionador, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Enrere)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBut_GuardarParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(seleccionador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enrere)
                    .addComponent(jBut_GuardarParticipant))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_GuardarParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_GuardarParticipantActionPerformed
        String jocSeleccionat = (String) seleccionador.getSelectedItem();
        this.dispose();
        
        JFrame pare = this.ventanaPare;
        
        if(jocSeleccionat.equals("KillTeam")) {
            AltaTaulaKillTeamJDialog AltaKillTeamJDialog = new AltaTaulaKillTeamJDialog(pare, true, gestor);
            AltaKillTeamJDialog.setVisible(true);
        }else if(jocSeleccionat.equals("MESBG")) {
            AltaTaulaMESBGJDialog AltaMESBGJDialog = new AltaTaulaMESBGJDialog(pare, true, gestor);
            AltaMESBGJDialog.setVisible(true);
        }else {
            JOptionPane.showMessageDialog(this, "Per favor, selecciona un joc vàlid.");            
        }
    }//GEN-LAST:event_jBut_GuardarParticipantActionPerformed

    private void EnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EnrereActionPerformed

    private void seleccionadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionadorActionPerformed
    }//GEN-LAST:event_seleccionadorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrere;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JButton jBut_GuardarParticipant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> seleccionador;
    // End of variables declaration//GEN-END:variables
}
